import csv
import json
import datetime

moonquakes = []

catalog = 'gagnepian_2006_catalog'
with open(f'data/{catalog}.csv', newline='') as file_handler:
    spamreader = csv.reader(file_handler, delimiter=',')
    n = 0
    for row in spamreader:
        if n != 0:
            info = ''
            description = ''
            if row[0] == 'M':
                info = 'Natural impact'
                description = "The second largest group of lunar seismic events, accounting for around 13% of all identified events, are generated by impacts. These impacts can originate from natural meteoroids or artificial sources. Artificial sources include spent stages of Saturn-V launch vehicles and lunar modules intentionally directed at the lunar surface to create seismic sources with specific timing and location. Natural impacts, particularly meteoroids with masses smaller than 1 kg, tend to cluster in time, correlating with known meteor showers (Nakamura et al., 1982; Oberst and Nakamura, 1991)"
            elif row[0] == 'SH':
                info = 'Shallow moonquake'
                description = "Shallow moonquakes have focal depths of less than 200 km and are rare, constituting less than 1% of all identified events. Despite their infrequency, they are notably larger than deep moonquakes (with moment magnitudes up to 4.7) and possess a low b value. In some cases, they are associated with exceptionally large stress drops (Oberst, 1987) (Nakamura, 1977)"
            elif row[0].startswith('A'):
                info = 'Deep moonquake'
                description = "Deep moonquakes, occurring deep within the Moon's depths, make up over 55% of lunar quakes. They follow periodic patterns tied to the Moon's position in the Sun-Earth-Moon system, with cycles of 1 month, 7 months, and 6 years. These patterns relate to lunar months (synodic, draconic, anomalistic) and are influenced by tidal forces. Recent studies have confirmed these patterns. Deep moonquakes are clustered into about 300 source regions or nests, mainly on the Moon's near side, due to their similar waveforms, indicating repeated occurrences in fixed locations"
            else: info = row[0]
            year = '19' + row[4][0:2]
            month = row[4][2:4]
            day = row[4][4:6]
            new_moonquake = {
                'code': f'{catalog}_{n}',
                'name': row[0],
                'mission': 'Apollo',
                'lat': row[1],
                'lng': row[2],
                'Info': info,
                'date': f'{year}-{month}-{day}',
                'description': description
            }
            moonquakes.append(new_moonquake)
        n += 1


catalog = 'lognonne_2003_catalog'
with open(f'data/{catalog}.csv', newline='') as file_handler:
    spamreader = csv.reader(file_handler, delimiter=',')
    n = 0
    for row in spamreader:
        if n != 0:
            info = ''
            description = ''
            if row[0] == 'M':
                info = 'Natural impact'
                description = "The second largest group of lunar seismic events, accounting for around 13% of all identified events, are generated by impacts. These impacts can originate from natural meteoroids or artificial sources. Artificial sources include spent stages of Saturn-V launch vehicles and lunar modules intentionally directed at the lunar surface to create seismic sources with specific timing and location. Natural impacts, particularly meteoroids with masses smaller than 1 kg, tend to cluster in time, correlating with known meteor showers (Nakamura et al., 1982; Oberst and Nakamura, 1991)"
            elif row[0] == 'SH':
                info = 'Shallow moonquake'
                description = "Shallow moonquakes have focal depths of less than 200 km and are rare, constituting less than 1% of all identified events. Despite their infrequency, they are notably larger than deep moonquakes (with moment magnitudes up to 4.7) and possess a low b value. In some cases, they are associated with exceptionally large stress drops (Oberst, 1987) (Nakamura, 1977)"
            elif row[0].startswith('A'):
                info = 'Deep moonquake'
                description = "Deep moonquakes, occurring deep within the Moon's depths, make up over 55% of lunar quakes. They follow periodic patterns tied to the Moon's position in the Sun-Earth-Moon system, with cycles of 1 month, 7 months, and 6 years. These patterns relate to lunar months (synodic, draconic, anomalistic) and are influenced by tidal forces. Recent studies have confirmed these patterns. Deep moonquakes are clustered into about 300 source regions or nests, mainly on the Moon's near side, due to their similar waveforms, indicating repeated occurrences in fixed locations"
            else: info = row[0]
            year = '19' + row[8][0:2]
            month = row[8][2:4]
            day = row[8][4:6]
            new_moonquake = {
                'code': f'{catalog}_{n}',
                'name': row[0],
                'mission': 'Apollo',
                'lat': row[1],
                'lng': row[2],
                'Info': info,
                'date': f'{year}-{month}-{day}',
                'description': description
            }
            moonquakes.append(new_moonquake)
        n += 1


catalog = 'nakamura_1979_sm_locations'
with open(f'data/{catalog}.csv', newline='') as file_handler:
    spamreader = csv.reader(file_handler, delimiter=',')
    n = 0
    for row in spamreader:
        if n != 0:
            date = datetime.datetime.strptime(f'{row[0]}{row[1]}', '%Y%j').date().strftime('%Y-%m-%d')
            new_moonquake = {
                'code': f'{catalog}_{n}',
                'name': f'{row[0]}_{row[1]}',
                'mission': 'Apollo',
                'lat': row[5],
                'lng': row[6],
                'Info': f'Magnitude: {row[7]}',
                'date': date,
                'description': "Shallow moonquakes have focal depths of less than 200 km and are rare, constituting less than 1% of all identified events. Despite their infrequency, they are notably larger than deep moonquakes (with moment magnitudes up to 4.7) and possess a low b value. In some cases, they are associated with exceptionally large stress drops (Oberst, 1987) (Nakamura, 1977)"
            }
            moonquakes.append(new_moonquake)
        n += 1


catalog = 'nakamura_1983_ai_locations'
with open(f'data/{catalog}.csv', newline='') as file_handler:
    spamreader = csv.reader(file_handler, delimiter=',')
    n = 0
    for row in spamreader:
        if n != 0:
            date = datetime.datetime.strptime(f'{row[3]}{row[4]}', '%y%j').date().strftime('%Y-%m-%d')
            new_moonquake = {
                'code': f'{catalog}_{n}',
                'name': f'AI {row[0]}',
                'mission': 'Apollo',
                'lat': row[1],
                'lng': row[2],
                'Info': f'Artificial impact {row[0]}',
                'date': date,
                'description': "The second largest group of lunar seismic events, accounting for around 13% of all identified events, are generated by impacts. These impacts can originate from natural meteoroids or artificial sources. Artificial sources include spent stages of Saturn-V launch vehicles and lunar modules intentionally directed at the lunar surface to create seismic sources with specific timing and location. Natural impacts, particularly meteoroids with masses smaller than 1 kg, tend to cluster in time, correlating with known meteor showers (Nakamura et al., 1982; Oberst and Nakamura, 1991)."
            }
            moonquakes.append(new_moonquake)
        n += 1


json_object = json.dumps(moonquakes, indent=4)
with open("../../moonquakes.json", "w") as outfile:
    outfile.write(json_object)
